### ISSUE TITLE
Provide some error message to kodi user interface when authorization with keys fail

### ISSUE THREAD

**Issue by Huxely** [hirsivaja/plugin.video.areena#12]
I noticed that out of the blue, my Areena-plugin stopped working. It just did nothing when I tried to search or list anything. First I suspected, that it had something to do with changing to LibreElec while ago, but after installing OpenElec and entering the keys again, no luck. Then I removed the plugin manually and installed it again, but no luck. Then I went digging in to the log, and found out, that I was gettin 401 answers from yle, so I suspected that something corrupted my keys. I went to yle site and check my keys, but they were correct. Then I tested the keys with yles own link and it gave me the same 401 error, so I contacted yle and they confirmed they have some problems in their own systems, so the error was not in the plugin or my keys,

Could it be possible to get some meaningfull error from the plugin in Kodi, when the authorization with API-keys fails, so in the future I don't have to reinstall everything because of non-woking keys?

**Comment by hirsivaja** [comment]
Could you post some examples from the log of these errors so I would know what to look for?

**Comment by miikalaaksonen** [comment]
Same happened to me.
Log from yesterday:
`
23:12:23  23.639418 T:3024020400  NOTICE: Running database version Addons20
23:12:23  23.646734 T:3024020400  NOTICE: Running database version ViewModes6
23:12:23  23.656311 T:3024020400  NOTICE: Running database version Textures13
23:12:23  23.692101 T:3024020400  NOTICE: Running database version MyMusic56
23:12:23  23.734228 T:3024020400  NOTICE: Running database version MyVideos99
23:12:23  23.743860 T:3024020400  NOTICE: Running database version TV29
23:12:23  23.752481 T:3024020400  NOTICE: Running database version Epg11
23:12:23  23.759880 T:3024020400  NOTICE: start dvd mediatype detection
23:12:25  26.076544 T:3024020400 WARNING: JSONRPC: Could not parse type "Setting.Details.SettingList"
23:12:26  26.437328 T:3024020400  NOTICE: ActiveAE DSP - starting
23:12:26  26.464808 T:3024020400  NOTICE: initialize done
23:12:26  26.475960 T:3024020400  NOTICE: Running the application...
23:12:28  28.421648 T:3024020400  NOTICE: starting zeroconf publishing
23:12:28  28.425648 T:3024020400  NOTICE: WebServer: Started the webserver
23:12:28  28.426096 T:3024020400  NOTICE: starting upnp client
23:12:28  28.515129 T:3024020400  NOTICE: starting upnp renderer
23:12:28  28.624422 T:2675962864  NOTICE: ES: Starting UDP Event server on 0.0.0.0:9777
23:12:28  28.624865 T:2675962864  NOTICE: UDP: Listening on port 9777
23:12:32  32.581188 T:2838811632  NOTICE: Your platform (armv6 System.Platform.Linux)
23:13:03  63.802048 T:2838811632  NOTICE: libspotify: notified main thread
23:13:03  63.818474 T:2838811632  NOTICE: Bitrate label is 320kbps
23:13:18  78.605225 T:2580542448   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IOError'>
                                            Error Contents: ('http error', 401, 'Unauthorized', <httplib.HTTPMessage instance at 0x96935940>)
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.areena/main.py", line 932, in <module>
                                                router(sys.argv[2][1:])
                                              File "/home/osmc/.kodi/addons/plugin.video.areena/main.py", line 913, in router
                                                list_categories(base_category)
                                              File "/home/osmc/.kodi/addons/plugin.video.areena/main.py", line 145, in list_categories
                                                listing = list_sub_categories(base_category)
                                              File "/home/osmc/.kodi/addons/plugin.video.areena/main.py", line 158, in list_sub_categories
                                                categories = get_categories()
                                              File "/home/osmc/.kodi/addons/plugin.video.areena/main.py", line 86, in get_categories
                                                return get_areena_api_json_data('programs', 'categories.json', [])
                                              File "/home/osmc/.kodi/addons/plugin.video.areena/main.py", line 64, in get_areena_api_json_data
                                                response = get_url_response(url)
                                              File "/home/osmc/.kodi/addons/plugin.video.areena/main.py", line 703, in get_url_response
                                                raise error
                                            IOError: ('http error', 401, 'Unauthorized', <httplib.HTTPMessage instance at 0x96935940>)
                                            -->End of Python script error report<--
23:13:19  79.591064 T:3024020400   ERROR: GetDirectory - Error getting plugin://plugin.video.areena/?action=categories&base=5-130
23:13:19  79.601135 T:3024020400   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.areena/?action=categories&base=5-130) failed
23:13:22  82.313858 T:2813645808 WARNING: CSkinInfo: failed to load skin settings
23:14:36 156.521500 T:2794771440   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IOError'>
                                            Error Contents: ('http error', 401, 'Unauthorized', <httplib.HTTPMessage instance at 0xa079a0a8>)
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.areena/main.py", line 932, in <module>
                                                router(sys.argv[2][1:])
                                              File "/home/osmc/.kodi/addons/plugin.video.areena/main.py", line 913, in router
                                                list_categories(base_category)
                                              File "/home/osmc/.kodi/addons/plugin.video.areena/main.py", line 145, in list_categories
                                                listing = list_sub_categories(base_category)
                                              File "/home/osmc/.kodi/addons/plugin.video.areena/main.py", line 158, in list_sub_categories
                                                categories = get_categories()
                                              File "/home/osmc/.kodi/addons/plugin.video.areena/main.py", line 86, in get_categories
                                                return get_areena_api_json_data('programs', 'categories.json', [])
                                              File "/home/osmc/.kodi/addons/plugin.video.areena/main.py", line 64, in get_areena_api_json_data
                                                response = get_url_response(url)
                                              File "/home/osmc/.kodi/addons/plugin.video.areena/main.py", line 703, in get_url_response
                                                raise error
                                            IOError: ('http error', 401, 'Unauthorized', <httplib.HTTPMessage instance at 0xa079a0a8>)
                                            -->End of Python script error report<--
23:14:36 157.060349 T:3024020400   ERROR: GetDirectory - Error getting plugin://plugin.video.areena/?action=categories&base=5-130
23:14:36 157.067017 T:3024020400   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.areena/?action=categories&base=5-130) failed

`

**Comment by Huxely** [comment]
Looks very familiar, I think my log was similar. I'll check when I get to my home network. Maybe the error can be replicated by inputting the keys wrong?

**Comment by Huxely** [comment]
Yeah same here

17:33:25 T:140388757124864   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IOError'>
                                            Error Contents: ('http error', 401, 'Unauthorized', <httplib.HTTPMessage instance at 0x7faf150ea1b8>)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.areena/main.py", line 932, in <module>
                                                router(sys.argv[2][1:])
                                              File "/storage/.kodi/addons/plugin.video.areena/main.py", line 913, in router
                                                list_categories(base_category)
                                              File "/storage/.kodi/addons/plugin.video.areena/main.py", line 145, in list_categories
                                                listing = list_sub_categories(base_category)
                                              File "/storage/.kodi/addons/plugin.video.areena/main.py", line 158, in list_sub_categories
                                                categories = get_categories()
                                              File "/storage/.kodi/addons/plugin.video.areena/main.py", line 86, in get_categories
                                                return get_areena_api_json_data('programs', 'categories.json', [])
                                              File "/storage/.kodi/addons/plugin.video.areena/main.py", line 64, in get_areena_api_json_data
                                                response = get_url_response(url)
                                              File "/storage/.kodi/addons/plugin.video.areena/main.py", line 703, in get_url_response
                                                raise error
                                            IOError: ('http error', 401, 'Unauthorized', <httplib.HTTPMessage instance at 0x7faf150ea1b8>)
                                            -->End of Python script error report<--
17:33:26 T:140390096074816   ERROR: GetDirectory - Error getting plugin://plugin.video.areena/?action=categories&base=5-130
17:33:26 T:140390096074816   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.areena/?action=categories&base=5-130) failed
17:33:26 T:140390096074816   ERROR: unable to load:/storage/.kodi/addons/skin.confluence/720p/DialogKaiToast.xml, Line 0
                                            Failed to open file
17:33:27 T:140388757124864   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IOError'>
                                            Error Contents: ('http error', 401, 'Unauthorized', <httplib.HTTPMessage instance at 0x7faf14895c20>)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.areena/main.py", line 932, in <module>
                                                router(sys.argv[2][1:])
                                              File "/storage/.kodi/addons/plugin.video.areena/main.py", line 913, in router
                                                list_categories(base_category)
                                              File "/storage/.kodi/addons/plugin.video.areena/main.py", line 145, in list_categories
                                                listing = list_sub_categories(base_category)
                                              File "/storage/.kodi/addons/plugin.video.areena/main.py", line 158, in list_sub_categories
                                                categories = get_categories()
                                              File "/storage/.kodi/addons/plugin.video.areena/main.py", line 86, in get_categories
                                                return get_areena_api_json_data('programs', 'categories.json', [])
                                              File "/storage/.kodi/addons/plugin.video.areena/main.py", line 64, in get_areena_api_json_data
                                                response = get_url_response(url)
                                              File "/storage/.kodi/addons/plugin.video.areena/main.py", line 703, in get_url_response
                                                raise error
                                            IOError: ('http error', 401, 'Unauthorized', <httplib.HTTPMessage instance at 0x7faf14895c20>)
                                            -->End of Python script error report<--
