### ISSUE TITLE
Live TV worked yesterday, stop after Kodi Update

### ISSUE THREAD

**Issue by raspikodi4ever** [hirsivaja/plugin.video.areena#29]
I ran into a problem after updating from LibreElec Kodi 17 Krypton to 18 Leia today, yesterday I was watching Yle Live TV with this add-on normally, but today all I get is this error:

2019-04-08 21:31:32.928 T:1570440048 WARNING: plugin.video.areena: No publication with 'currently': {u'fi': u'Yle Areena: J\xe4\xe4kiekon naisten MM: Kanada - Ven\xe4j\xe4'}
2019-04-08 21:31:32.933 T:1570440048   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode characters in position 29-30: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.areena/main.py", line 1122, in <module>
                                                router(sys.argv[2][1:])
                                              File "/storage/.kodi/addons/plugin.video.areena/main.py", line 1108, in router
                                                live_tv_channels(path)
                                              File "/storage/.kodi/addons/plugin.video.areena/main.py", line 512, in live_tv_channels
                                                get_color('menuItemColor'),  get_translation(32072) + title))
                                            UnicodeEncodeError: 'ascii' codec can't encode characters in position 29-30: ordinal not in range(128)
                                            -->End of Python script error report<--
2019-04-08 21:31:33.122 T:1339761520   ERROR: GetDirectory - Error getting plugin://plugin.video.areena/?action=live
2019-04-08 21:31:33.124 T:1937612816   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.areena/?action=live) failed

I saw this issue had been brought up, solved and closes in 2018 Jan. [https://github.com/hirsivaja/plugin.video.areena/issues/25](https://github.com/hirsivaja/plugin.video.areena/issues/25)

Today I installed Yle Areena addon from freshly downloaded master .zip, I use fi_latin keyboard layout for LibreElec system and English for interface language with default character set and Swedish QWERTY in regional settings, if it makes difference. Everything else in Areena addon has been working normally.

**Comment by hirsivaja** [comment]
I think you might have an older version of the plugin in use. In your error message it says:

> File "/storage/.kodi/addons/plugin.video.areena/main.py", line 512, in live_tv_channels
> get_color('menuItemColor'), get_translation(32072) + title))

If we look at the master version of the [main.py](https://github.com/hirsivaja/plugin.video.areena/blob/master/main.py#L512) we can see that line 512 contains something totally different.

Can you check your version and update if necessary?

**Comment by hirsivaja** [comment]
Closed since no information provided. Seems to work in current version.
