### ISSUE TITLE
Kodi 19 support

### ISSUE THREAD

**Issue by FunctionalHacker** [hirsivaja/plugin.video.areena#38]
I was testing Kodi 19 alpha the other day and noticed that this addon is not supported. 

I have moved back to 18 but if need be, I can upgrade again and provide debug logs and such. I'm not familiar with Kodi development so I'm just not sure what is needed.

EDIT: If I recall correctly, one of the big changes in Kodi 19 was the move to Python 3. This might be a bigger undertaking as I initially thought

**Comment by hirsivaja** [comment]
Hi Marko,
now you can try the plugin from python3 branch
https://github.com/hirsivaja/plugin.video.areena/archive/python3.zip

Still a beta version but main functionality should be working.

**Comment by FunctionalHacker** [comment]
Thanks! I will test it in the following few days when I get a chance.

Kodi 19 release seems to be pretty close, so we should probably start looking at the transition. I think keeping the master brangh for Kodi 18 until the release of 19, after that, copy the Kodi 18 version to a new branch and merge the python3 branch to master. What do you think?

**Comment by FunctionalHacker** [comment]
Hi again! Sorry, life happened and I never got to trying out the python3 branch. I just switched my main Kodi install to 19, so I was able to catch a debug log for you

<details>
  <summary>kodi.log</summary>
2021-02-10 17:56:58.403 T:24180   ERROR <general>: Control 55 in window 10025 has been asked to focus, but it can't
2021-02-10 17:56:58.430 T:30329    INFO <general>: initializing python engine.
2021-02-10 17:56:58.742 T:30329 WARNING <general>: xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.
2021-02-10 17:56:58.746 T:30329    INFO <general>: CPythonInvoker(69, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.areena/main.py): script successfully run
2021-02-10 17:56:59.360 T:30329 WARNING <general>: CPythonInvoker(69, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.areena/main.py): the python script "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.areena/main.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE
2021-02-10 17:56:59.360 T:30329    INFO <general>: Python interpreter stopped
2021-02-10 17:57:11.490 T:30374    INFO <general>: initializing python engine.
2021-02-10 17:57:11.796 T:30374 WARNING <general>: xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.
2021-02-10 17:57:11.808 T:30374    INFO <general>: CPythonInvoker(70, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.areena/main.py): script successfully run
2021-02-10 17:57:12.403 T:30374 WARNING <general>: CPythonInvoker(70, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.areena/main.py): the python script "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.areena/main.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE
2021-02-10 17:57:12.403 T:30374    INFO <general>: Python interpreter stopped
2021-02-10 17:57:14.103 T:30379    INFO <general>: initializing python engine.
2021-02-10 17:57:14.419 T:30379 WARNING <general>: xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.
2021-02-10 17:57:14.431 T:30384    INFO <general>: initializing python engine.
2021-02-10 17:57:15.068 T:30384 WARNING <general>: xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.
2021-02-10 17:57:15.075 T:30384    INFO <general>: CPythonInvoker(72, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.autocompletion/plugin.py): script successfully run
2021-02-10 17:57:15.786 T:30384    INFO <general>: Python interpreter stopped
2021-02-10 17:57:18.796 T:30425    INFO <general>: initializing python engine.
2021-02-10 17:57:19.479 T:30425 WARNING <general>: xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.
2021-02-10 17:57:19.492 T:30425 WARNING <general>: xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.
2021-02-10 17:57:19.611 T:30425    INFO <general>: CPythonInvoker(73, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.autocompletion/plugin.py): script successfully run
2021-02-10 17:57:20.277 T:30425    INFO <general>: Python interpreter stopped
2021-02-10 17:57:20.955 T:30379 WARNING <general>: Attempt to use invalid handle 48
2021-02-10 17:57:20.956 T:30379    INFO <general>: CPythonInvoker(71, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.areena/main.py): script successfully run
2021-02-10 17:57:21.570 T:30379 WARNING <general>: CPythonInvoker(71, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.areena/main.py): the python script "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.areena/main.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE
2021-02-10 17:57:21.570 T:30379    INFO <general>: Python interpreter stopped
2021-02-10 17:57:21.699 T:30432    INFO <general>: initializing python engine.
2021-02-10 17:57:21.998 T:30432 WARNING <general>: xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.
2021-02-10 17:57:23.173 T:30432    INFO <general>: CPythonInvoker(74, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.areena/main.py): script successfully run
2021-02-10 17:57:23.839 T:30432 WARNING <general>: CPythonInvoker(74, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.areena/main.py): the python script "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.areena/main.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE
2021-02-10 17:57:23.839 T:30432    INFO <general>: Python interpreter stopped
2021-02-10 17:57:27.251 T:30477    INFO <general>: initializing python engine.
2021-02-10 17:57:27.535 T:30477 WARNING <general>: xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.
2021-02-10 17:57:29.015 T:30477   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'UnicodeEncodeError'>
                                                   Error Contents: 'ascii' codec can't encode characters in position 80-81: ordinal not in range(128)
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.areena/main.py", line 1227, in <module>
                                                       router(sys.argv[2][1:])
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.areena/main.py", line 1159, in router
                                                       play_stream(params['stream'])
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.areena/main.py", line 444, in play_stream
                                                       subtitle_file = download_subtitle(subtitle['uri'], "{0}.{1}.sub".format(media_id, subtitle['lang']))
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.areena/main.py", line 498, in download_subtitle
                                                       local_file.write(response)
                                                   UnicodeEncodeError: 'ascii' codec can't encode characters in position 80-81: ordinal not in range(128)
                                                   -->End of Python script error report<--
                                                   
2021-02-10 17:57:29.681 T:30477 WARNING <general>: CPythonInvoker(75, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.areena/main.py): the python script "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.areena/main.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE
2021-02-10 17:57:29.681 T:30477    INFO <general>: Python interpreter stopped
2021-02-10 17:57:29.698 T:24180   ERROR <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.areena/?action=play&stream=1-4216770]
</details>

Seems that the directory listings, search etc. are working perfectly but I was not able to play anything. During the log I went to do a series search for "sorjonen" picked the series and tried to play the first shown episode. Hope this helps.

**Comment by hirsivaja** [comment]
This seems to be working in my environment. Have not tested with Android though. I will try to see if there is some differences in the Android version

**Comment by hirsivaja** [comment]
Made a potential fix. Still works on my environments and might fix the issue on Android

**Comment by FunctionalHacker** [comment]
Awesome, the latest version of the python3 branch fixed playback for me!

**Comment by hirsivaja** [comment]
Created a new maintenance branch 'python2' for legacy support. Merged changes from 'python3' branch to 'master'.

I will test the plugin once Kodi 19 official release comes, but there should not be any functional changes to the current tested RC1.
